version: '3.5'

services:
  node:
    container_name: <node-test>
    build:
      context: .
      dockerfile: node.dockerfile
    command: bash startpm2.sh <env variable>
    ports:
       - "3001:3001"
       - "8001:8001"
    external_links:
       - mysql
       - redis
    networks:
      - nodeapp-network
      - db-net

networks:
  nodeapp-network:
    driver: bridge
    name: node-net
  db-net:
    external: true
