version: '3.5'

services:
  node:
    build:
      context: .
      dockerfile: node.dockerfile
    command: bash startpm2.sh <env variable>
    ports:
       - "3001"
    external_links:
       - mysql
       - redis
    networks:
      - nodeapp-network
      - db-net

  lb:
    image: dockercloud/haproxy
    ports:
      - <haproxy-port>:80
    links:
      - node
    networks:
      - nodeapp-network
      - db-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  nodeapp-network:
    driver: bridge
    name: node-net
  db-net:
    external: true
